name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy to InfinityFree
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Latest Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📡 Sync Files to santafebeachclub.wuaze.com via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /santafebeachclub.wuaze.com/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env.example
            **/README.md
            **/wapiti_report.txt
            **/__pycache__/**
            **/*.bat
